#!/usr/bin/env bash

# Keep this byte-for-byte aligned with the Casks/auto.rb emitted for v0.50.70
# by the release-pinned GoReleaser v2.17.0. Only version and checksums vary.
render_homebrew_cask() {
  local output="$1" version="$2"
  local darwin_amd64_sha="$3" darwin_arm64_sha="$4"
  local linux_amd64_sha="$5" linux_arm64_sha="$6"
  cat >"$output" <<EOF
# This file was generated by GoReleaser. DO NOT EDIT.
cask "auto" do
  version "$version"

  on_macos do
    on_intel do
      sha256 "$darwin_amd64_sha"
      url "https://github.com/Insajin/autopus-adk/releases/download/v#{version}/autopus-adk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "$darwin_arm64_sha"
      url "https://github.com/Insajin/autopus-adk/releases/download/v#{version}/autopus-adk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "$linux_amd64_sha"
      url "https://github.com/Insajin/autopus-adk/releases/download/v#{version}/autopus-adk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "$linux_arm64_sha"
      url "https://github.com/Insajin/autopus-adk/releases/download/v#{version}/autopus-adk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "auto"
  desc "Agentic Development Kit for coding CLIs (the auto CLI)"
  homepage "https://github.com/Insajin/autopus-adk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "auto"

  # No zap stanza required

end
EOF
}

render_homebrew_formula_bridge() {
  local output="$1" tag="$2" version="$3"
  local darwin_amd64_sha="$4" darwin_arm64_sha="$5"
  local linux_amd64_sha="$6" linux_arm64_sha="$7"
  cat >"$output" <<EOF
# typed: false
# frozen_string_literal: true

# One-release migration bridge for users of the legacy Formula.
class Auto < Formula
  desc "Agentic Development Kit for coding CLIs (the auto CLI)"
  homepage "https://github.com/Insajin/autopus-adk"
  version "$version"
  license "MIT"
  deprecate! date: "2026-07-16", because: "is distributed as a signed cask", replacement_cask: "auto"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Insajin/autopus-adk/releases/download/$tag/autopus-adk_${version}_darwin_amd64.tar.gz"
      sha256 "$darwin_amd64_sha"
    end
    if Hardware::CPU.arm?
      url "https://github.com/Insajin/autopus-adk/releases/download/$tag/autopus-adk_${version}_darwin_arm64.tar.gz"
      sha256 "$darwin_arm64_sha"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-adk/releases/download/$tag/autopus-adk_${version}_linux_amd64.tar.gz"
      sha256 "$linux_amd64_sha"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Insajin/autopus-adk/releases/download/$tag/autopus-adk_${version}_linux_arm64.tar.gz"
      sha256 "$linux_arm64_sha"
    end
  end

  def install
    bin.install "auto"
  end

  def caveats
    <<~EOS
      This Formula is a one-release migration bridge. Migrate to the signed Cask:
        brew uninstall --formula auto
        brew install --cask Insajin/autopus/auto
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/auto version")
  end
end
EOF
}
