package scaffold

// captureFixtureBody is the emitted .autopus/qa/capture/autopus-capture.fixture.cjs
// asset. The body is split across two files only to respect the 300-line source
// limit; the cut is at a function boundary so each half stays readable JS.
const captureFixtureBody = captureFixtureHeadJS + captureFixtureTailJS

const captureFixtureHeadJS = `'use strict';

// Autopus QAMESH GUI capture producer - Playwright fixture.
//
// Generated by 'auto qa init'; the project owns this file. The harness never
// drives Playwright: it allocates a capture directory and declares the policy
// this fixture honors. One shard per test lands in <CAPTURE_DIR>/shards/ and
// the companion reporter merges the shards into capture-index.json.
//
// Capture never decides whether a test passes. Every capture step is guarded
// and a failure is recorded as capture_error on the shard, never thrown.

const base = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const POLICY_PATH_ENV = 'AUTOPUS_QAMESH_GUI_CAPTURE_POLICY_PATH';
const CAPTURE_DIR_ENV = 'AUTOPUS_QAMESH_GUI_CAPTURE_DIR';
// Bounds mirror pkg/qa/capture/validate.go. Exceeding one rejects the whole
// index, so evidence is truncated here while the counters stay exact.
const MAX = { console: 200, network: 500, actions: 200, text: 2000, ref: 400, target: 200, errors: 5 };
const SEVERITY_RANK = { info: 1, warning: 2, error: 3 };
const STATUS = { passed: 'passed', failed: 'failed', skipped: 'skipped' };
const HTTP_METHOD = /^[A-Z]{3,10}$/;
const ANSI = /\u001b\[[0-9;]*[A-Za-z]/g;
// Only the first argument of these APIs is recorded: the second argument of
// fill/press carries typed text, which can be a credential.
const WRAPPED_APIS = ['goto', 'click', 'fill', 'press', 'check', 'selectOption', 'waitForSelector'];

function safePolicy() {
  try {
    const policyPath = process.env[POLICY_PATH_ENV];
    if (!policyPath) return null;
    const raw = JSON.parse(fs.readFileSync(policyPath, 'utf8'));
    const origins = Array.isArray(raw.allowed_origins) ? raw.allowed_origins : [];
    return {
      dir: process.env[CAPTURE_DIR_ENV] || path.dirname(policyPath),
      mode: String(raw.mode || 'off'),
      streams: Array.isArray(raw.streams) ? raw.streams.map(String) : [],
      screenshot: String(raw.screenshot || 'off'),
      threshold: SEVERITY_RANK[String(raw.console_severity || 'info')] || SEVERITY_RANK.info,
      origins: origins.map(function (origin) { return String(origin).replace(/\/+$/, ''); }),
    };
  } catch (error) {
    return null;
  }
}

function plain(value) {
  return String(value === undefined || value === null ? '' : value).replace(ANSI, '').replace(/\s+/g, ' ').trim();
}

function errorText(error) {
  return (error && plain(error.message || error.value || error)) || 'unknown error';
}

function pushError(state, label, error) {
  if (state.errors.length < MAX.errors) state.errors.push(label + ': ' + errorText(error));
}

async function guard(state, label, fn) {
  try {
    return await fn();
  } catch (error) {
    pushError(state, label, error);
    return null;
  }
}

// urlRef turns a URL into the reference shape the contract accepts: an
// origin-relative path or origin:<index><path>. Query and fragment are dropped
// and anything outside a conservative path alphabet is folded to '-', because
// that is where tokens and credentials hide. A URL matching no allowed origin
// yields '' so the caller drops it instead of recording a third-party host.
function urlRef(policy, value) {
  const raw = String(value || '');
  if (!raw) return '';
  const stripped = raw.split('#')[0].split('?')[0];
  for (let index = 0; index < policy.origins.length; index += 1) {
    const origin = policy.origins[index];
    if (!origin) continue;
    if (stripped === origin || stripped === origin + '/') return 'origin:' + index;
    if (stripped.indexOf(origin + '/') === 0) return 'origin:' + index + safeRefPath(stripped.slice(origin.length));
  }
  if (stripped.indexOf('/') === 0 && stripped.indexOf('//') !== 0) return safeRefPath(stripped);
  return '';
}

function safeRefPath(value) {
  const folded = value.replace(/[^A-Za-z0-9._~/-]/g, '-');
  return folded.length > MAX.ref ? folded.slice(0, MAX.ref) : folded;
}

function recordConsole(state, severity, text, sourceRef) {
  if (severity === 'error') state.console.errors += 1;
  else if (severity === 'warning') state.console.warnings += 1;
  else state.console.infos += 1;
  const body = plain(text);
  if (!body || SEVERITY_RANK[severity] < state.threshold) return;
  if (state.console.messages.length >= MAX.console) return;
  const message = { severity: severity, text: body.slice(0, MAX.text) };
  if (sourceRef) message.source_ref = sourceRef;
  state.console.messages.push(message);
}

function attachListeners(page, policy, state) {
  if (policy.streams.includes('console')) {
    page.on('console', function (message) {
      const type = message.type();
      const severity = type === 'error' || type === 'warning' ? type : 'info';
      recordConsole(state, severity, message.text(), urlRef(policy, (message.location() || {}).url));
    });
    page.on('pageerror', function (error) { recordConsole(state, 'error', errorText(error), ''); });
  }
  if (!policy.streams.includes('network')) return;
  // Counters are incremented synchronously so they stay exact even after the
  // per-entry budget is spent; only the entry detail is capped.
  page.on('response', function (response) {
    if (response.status() >= 400) state.network.failures += 1;
  });
  page.on('requestfinished', function (request) {
    state.network.requests += 1;
    if (state.pending.length < MAX.network) state.pending.push(recordRequest(policy, state, request, false));
  });
  page.on('requestfailed', function (request) {
    state.network.requests += 1;
    state.network.failures += 1;
    if (state.pending.length < MAX.network) state.pending.push(recordRequest(policy, state, request, true));
  });
}

`
