package scaffold

// captureFixtureBody is the emitted .autopus/qa/capture/autopus-capture.fixture.cjs asset.
const captureFixtureBody = `'use strict';

// Autopus QAMESH GUI capture producer - Playwright fixture.
//
// Generated by 'auto qa init'; the project owns this file. The harness never
// drives Playwright: it allocates a capture directory and declares the policy
// this fixture honors. One shard per test lands in <CAPTURE_DIR>/shards/ and
// the companion reporter merges the shards into capture-index.json.
//
// Capture never decides whether a test passes. Every capture step is guarded
// and a failure is recorded as capture_error on the shard, never thrown.

const base = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const POLICY_PATH_ENV = 'AUTOPUS_QAMESH_GUI_CAPTURE_POLICY_PATH';
const CAPTURE_DIR_ENV = 'AUTOPUS_QAMESH_GUI_CAPTURE_DIR';
// Bounds mirror pkg/qa/capture/validate.go. Exceeding one rejects the whole
// index, so evidence is truncated here while the counters stay exact.
const MAX = { console: 200, network: 500, actions: 200, text: 2000, ref: 400, target: 200, errors: 5 };
const SEVERITY_RANK = { info: 1, warning: 2, error: 3 };
const STATUS = { passed: 'passed', failed: 'failed', skipped: 'skipped' };
const HTTP_METHOD = /^[A-Z]{3,10}$/;
const ANSI = /\u001b\[[0-9;]*[A-Za-z]/g;
// Only the first argument of these APIs is recorded: the second argument of
// fill/press carries typed text, which can be a credential.
const WRAPPED_APIS = ['goto', 'click', 'fill', 'press', 'check', 'selectOption', 'waitForSelector'];

function safePolicy() {
  try {
    const policyPath = process.env[POLICY_PATH_ENV];
    if (!policyPath) return null;
    const raw = JSON.parse(fs.readFileSync(policyPath, 'utf8'));
    const origins = Array.isArray(raw.allowed_origins) ? raw.allowed_origins : [];
    return {
      dir: process.env[CAPTURE_DIR_ENV] || path.dirname(policyPath),
      mode: String(raw.mode || 'off'),
      streams: Array.isArray(raw.streams) ? raw.streams.map(String) : [],
      screenshot: String(raw.screenshot || 'off'),
      threshold: SEVERITY_RANK[String(raw.console_severity || 'info')] || SEVERITY_RANK.info,
      origins: origins.map(function (origin) { return String(origin).replace(/\/+$/, ''); }),
    };
  } catch (error) {
    return null;
  }
}

function plain(value) {
  return String(value === undefined || value === null ? '' : value).replace(ANSI, '').replace(/\s+/g, ' ').trim();
}

function errorText(error) {
  return (error && plain(error.message || error.value || error)) || 'unknown error';
}

function pushError(state, label, error) {
  if (state.errors.length < MAX.errors) state.errors.push(label + ': ' + errorText(error));
}

async function guard(state, label, fn) {
  try {
    return await fn();
  } catch (error) {
    pushError(state, label, error);
    return null;
  }
}

// urlRef turns a URL into the reference shape the contract accepts: an
// origin-relative path or origin:<index><path>. Query and fragment are dropped
// and anything outside a conservative path alphabet is folded to '-', because
// that is where tokens and credentials hide. A URL matching no allowed origin
// yields '' so the caller drops it instead of recording a third-party host.
function urlRef(policy, value) {
  const raw = String(value || '');
  if (!raw) return '';
  const stripped = raw.split('#')[0].split('?')[0];
  for (let index = 0; index < policy.origins.length; index += 1) {
    const origin = policy.origins[index];
    if (!origin) continue;
    if (stripped === origin || stripped === origin + '/') return 'origin:' + index;
    if (stripped.indexOf(origin + '/') === 0) return 'origin:' + index + safeRefPath(stripped.slice(origin.length));
  }
  if (stripped.indexOf('/') === 0 && stripped.indexOf('//') !== 0) return safeRefPath(stripped);
  return '';
}

function safeRefPath(value) {
  const folded = value.replace(/[^A-Za-z0-9._~/-]/g, '-');
  return folded.length > MAX.ref ? folded.slice(0, MAX.ref) : folded;
}

function recordConsole(state, severity, text, sourceRef) {
  if (severity === 'error') state.console.errors += 1;
  else if (severity === 'warning') state.console.warnings += 1;
  else state.console.infos += 1;
  const body = plain(text);
  if (!body || SEVERITY_RANK[severity] < state.threshold) return;
  if (state.console.messages.length >= MAX.console) return;
  const message = { severity: severity, text: body.slice(0, MAX.text) };
  if (sourceRef) message.source_ref = sourceRef;
  state.console.messages.push(message);
}

function attachListeners(page, policy, state) {
  if (policy.streams.includes('console')) {
    page.on('console', function (message) {
      const type = message.type();
      const severity = type === 'error' || type === 'warning' ? type : 'info';
      recordConsole(state, severity, message.text(), urlRef(policy, (message.location() || {}).url));
    });
    page.on('pageerror', function (error) { recordConsole(state, 'error', errorText(error), ''); });
  }
  if (!policy.streams.includes('network')) return;
  // Counters are incremented synchronously so they stay exact even after the
  // per-entry budget is spent; only the entry detail is capped.
  page.on('response', function (response) {
    if (response.status() >= 400) state.network.failures += 1;
  });
  page.on('requestfinished', function (request) {
    state.network.requests += 1;
    if (state.pending.length < MAX.network) state.pending.push(recordRequest(policy, state, request, false));
  });
  page.on('requestfailed', function (request) {
    state.network.requests += 1;
    state.network.failures += 1;
    if (state.pending.length < MAX.network) state.pending.push(recordRequest(policy, state, request, true));
  });
}

async function recordRequest(policy, state, request, failed) {
  try {
    const method = String(request.method() || '').toUpperCase();
    const ref = urlRef(policy, request.url());
    if (!HTTP_METHOD.test(method) || !ref) return;
    const response = failed ? null : await request.response();
    const sizes = await request.sizes().catch(function () { return null; });
    const timing = request.timing() || {};
    if (state.network.entries.length >= MAX.network) return;
    state.network.entries.push({
      method: method,
      url_ref: ref,
      status: response ? response.status() : 0,
      resource_type: String(request.resourceType() || ''),
      duration_ms: timing.responseEnd > 0 ? Math.round(timing.responseEnd) : 0,
      bytes: sizes && sizes.responseBodySize > 0 ? sizes.responseBodySize : 0,
    });
  } catch (error) {
    pushError(state, 'network', error);
  }
}

function targetRef(policy, api, arg) {
  if (api === 'goto') return urlRef(policy, arg);
  if (typeof arg !== 'string') return '';
  return arg.length > MAX.target ? arg.slice(0, MAX.target) : arg;
}

function wrapActions(page, policy, state) {
  WRAPPED_APIS.forEach(function (api) {
    const original = page[api];
    if (typeof original !== 'function') return;
    page[api] = function () {
      const args = Array.prototype.slice.call(arguments);
      const started = Date.now();
      const record = function () {
        if (state.actions.length >= MAX.actions) return;
        const action = { api: api, duration_ms: Date.now() - started };
        const ref = targetRef(policy, api, args[0]);
        if (ref) action.target_ref = ref;
        state.actions.push(action);
      };
      return original.apply(page, args).then(
        function (value) { record(); return value; },
        function (error) { record(); throw error; });
    };
  });
}

function mediaRef(dir, rel, width, height) {
  const body = fs.readFileSync(path.join(dir, rel));
  if (!body.length) return null;
  const ref = {
    ref: rel,
    digest: 'sha256:' + crypto.createHash('sha256').update(body).digest('hex'),
    bytes: body.length,
    retention: 'local_only',
  };
  if (width > 0 && height > 0) { ref.width = width; ref.height = height; }
  return ref;
}

// slugFor is both the step_id and the media basename. The hash suffix keeps two
// tests with the same truncated title from colliding on one step_id.
function slugFor(testInfo) {
  const raw = (testInfo.titlePath || []).concat([String(testInfo.repeatEachIndex || 0), String(testInfo.retry || 0)]).join('-');
  const suffix = crypto.createHash('sha256').update(raw).digest('hex').slice(0, 8);
  const slug = raw.replace(/[^A-Za-z0-9._-]+/g, '-').replace(/^-+/, '').replace(/-+$/, '').slice(0, 90);
  return (slug || 'step') + '-' + suffix;
}

function specRef(testInfo) {
  const file = testInfo.file || '';
  const rel = path.relative((testInfo.config && testInfo.config.rootDir) || process.cwd(), file);
  if (!rel || path.isAbsolute(rel) || rel.indexOf('..') === 0) return path.basename(file) || 'spec';
  return rel.split(path.sep).join('/');
}

function failureSummary(testInfo, status) {
  const parts = (testInfo.errors || []).map(errorText).filter(Boolean);
  if (!parts.length && status !== 'passed' && status !== 'skipped') parts.push('test ' + status + ' without a reported error');
  return parts.join(' | ').slice(0, MAX.text);
}

function shouldShoot(policy, status) {
  if (!policy.streams.includes('screenshot') || status === 'skipped') return false;
  if (policy.screenshot === 'per-step') return true;
  return policy.screenshot === 'on-failure' && (status === 'failed' || status === 'blocked');
}

async function finish(page, testInfo, policy, state, startedAt) {
  const slug = slugFor(testInfo);
  const status = STATUS[testInfo.status] || 'blocked';
  await guard(state, 'network', function () { return Promise.all(state.pending); });
  const shard = {
    step_id: slug,
    title: plain(testInfo.title).slice(0, MAX.text),
    status: status,
    started_at: startedAt,
    ended_at: new Date().toISOString(),
    duration_ms: Math.max(0, Math.round(testInfo.duration || 0)),
    spec_ref: specRef(testInfo),
    actions: state.actions,
  };
  if (policy.streams.includes('console')) shard.console = state.console;
  if (policy.streams.includes('network')) shard.network = state.network;
  if (shouldShoot(policy, status)) {
    const rel = 'screenshots/' + slug + '.png';
    const ref = await guard(state, 'screenshot', async function () {
      fs.mkdirSync(path.join(policy.dir, 'screenshots'), { recursive: true });
      await page.screenshot({ path: path.join(policy.dir, rel) });
      const viewport = page.viewportSize() || { width: 0, height: 0 };
      return mediaRef(policy.dir, rel, viewport.width, viewport.height);
    });
    if (ref) shard.screenshot = ref;
  }
  if (policy.streams.includes('trace')) {
    await guard(state, 'trace_stop', async function () {
      fs.mkdirSync(path.join(policy.dir, 'traces'), { recursive: true });
      await page.context().tracing.stop({ path: path.join(policy.dir, 'traces', slug + '.zip') });
    });
  }
  const summary = failureSummary(testInfo, status);
  if (summary) shard.failure_summary = summary;
  if (state.errors.length) shard.capture_error = state.errors.join(' | ').slice(0, MAX.text);
  const target = path.join(policy.dir, 'shards', slug + '.json');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, JSON.stringify(shard, null, 2) + '\n');
}

const test = base.test.extend({
  autopusCapture: [
    async function autopusCapture({ page }, use, testInfo) {
      const policy = safePolicy();
      if (!policy || policy.mode === 'off') {
        // Outside a QAMESH run this fixture adds nothing: 'playwright test'
        // must behave exactly as it did before capture existed.
        await use(null);
        return;
      }
      const state = {
        threshold: policy.threshold,
        console: { errors: 0, warnings: 0, infos: 0, messages: [] },
        network: { requests: 0, failures: 0, entries: [] },
        actions: [], pending: [], errors: [],
      };
      if (policy.streams.includes('trace')) {
        await guard(state, 'trace_start', function () {
          return page.context().tracing.start({ screenshots: true, snapshots: true });
        });
      }
      attachListeners(page, policy, state);
      wrapActions(page, policy, state);
      const startedAt = new Date().toISOString();
      await use(state);
      await guard(state, 'finish', function () { return finish(page, testInfo, policy, state, startedAt); });
    },
    { auto: true },
  ],
});

module.exports = { test: test, expect: base.expect };
`
