package scaffold

// captureReporterBody is the emitted .autopus/qa/capture/autopus-capture.reporter.cjs asset.
const captureReporterBody = `'use strict';

// Autopus QAMESH GUI capture producer - Playwright reporter. Generated by
// 'auto qa init'; the project owns this file. It merges the shards the fixture
// wrote into one capture-index.json. The Go decoder uses DisallowUnknownFields,
// so every value is projected onto exactly the keys the contract defines: one
// extra key rejects the whole index.

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const POLICY_PATH_ENV = 'AUTOPUS_QAMESH_GUI_CAPTURE_POLICY_PATH';
const CAPTURE_DIR_ENV = 'AUTOPUS_QAMESH_GUI_CAPTURE_DIR';
const INDEX_PATH_ENV = 'AUTOPUS_QAMESH_GUI_CAPTURE_INDEX_PATH';
const SCHEMA_VERSION = 'qamesh.gui_capture_index.v1';
// specs is capped so command fits MaxReplayCommandLen (32); other bounds mirror capture/validate.go.
const MAX = { text: 2000, ref: 512, target: 200, media: 200, specs: 27, stepID: 120 };
const STATUSES = { passed: true, failed: true, skipped: true, blocked: true };
// A replay argument must run without a shell. The backtick is spelled by code
// point so this file stays embeddable in a Go raw string literal.
const UNSAFE_ARG_CHARS = ';&|<>$\r\n\\' + String.fromCharCode(96);

function safePolicy() {
  try {
    const policyPath = process.env[POLICY_PATH_ENV];
    if (!policyPath) return null;
    const raw = JSON.parse(fs.readFileSync(policyPath, 'utf8'));
    return {
      dir: process.env[CAPTURE_DIR_ENV] || path.dirname(policyPath),
      journeyId: String(raw.journey_id || ''),
      mode: String(raw.mode || 'off'),
      streams: Array.isArray(raw.streams) ? raw.streams.map(String) : [],
      replayScript: String(raw.replay_script || 'off'),
    };
  } catch (error) {
    return null;
  }
}

function compare(left, right) {
  const a = String(left || '');
  const b = String(right || '');
  return a === b ? 0 : (a < b ? -1 : 1);
}

function count(value) {
  const number = Number(value);
  return Number.isFinite(number) && number > 0 ? Math.round(number) : 0;
}

function clip(value, limit) {
  return String(value === undefined || value === null ? '' : value).slice(0, limit);
}

function safeArg(value) {
  const text = String(value || '');
  if (!text.trim()) return false;
  for (let index = 0; index < UNSAFE_ARG_CHARS.length; index += 1) {
    if (text.indexOf(UNSAFE_ARG_CHARS.charAt(index)) !== -1) return false;
  }
  return true;
}

function loadShards(dir) {
  const shards = [];
  const root = path.join(dir, 'shards');
  let names = [];
  try { names = fs.readdirSync(root); } catch (error) { return shards; }
  names.forEach(function (name) {
    if (!/\.json$/.test(name)) return;
    // One unreadable shard must not discard the rest of the run.
    try { shards.push(JSON.parse(fs.readFileSync(path.join(root, name), 'utf8'))); } catch (error) { return; }
  });
  shards.sort(function (left, right) {
    return compare(left.started_at, right.started_at) || compare(left.step_id, right.step_id);
  });
  return shards;
}

function stepID(value, order, seen) {
  let id = String(value || '').replace(/[^A-Za-z0-9._:-]/g, '-').slice(0, MAX.stepID) || 'step-' + order;
  // A duplicate step_id rejects the index, so a collision is renamed instead.
  if (seen[id]) id = id.slice(0, MAX.stepID - 8) + '-' + order;
  seen[id] = true;
  return id;
}

// Diagnostics ride in failure_summary: the shard-only capture_error field has no
// place in the contract, and inventing a key for it would reject the index.
function failureSummary(shard, status) {
  const parts = [];
  if (shard.failure_summary) parts.push(String(shard.failure_summary));
  if (shard.capture_error) parts.push('capture_error: ' + String(shard.capture_error));
  if (!parts.length && (status === 'failed' || status === 'blocked')) parts.push('step ' + status + ' without a reported error');
  return parts.join(' | ').slice(0, MAX.text);
}

function actionOf(raw) {
  const action = { api: String((raw && raw.api) || 'unknown') };
  if (raw && raw.target_ref) action.target_ref = clip(raw.target_ref, MAX.target);
  if (raw && count(raw.duration_ms) > 0) action.duration_ms = count(raw.duration_ms);
  return action;
}

function mediaRefOf(raw) {
  const ref = { ref: String(raw.ref || ''), digest: String(raw.digest || ''), bytes: count(raw.bytes), retention: 'local_only' };
  if (count(raw.width) > 0) ref.width = count(raw.width);
  if (count(raw.height) > 0) ref.height = count(raw.height);
  return ref;
}

function consoleOf(raw) {
  const summary = { errors: count(raw.errors), warnings: count(raw.warnings) };
  if (count(raw.infos) > 0) summary.infos = count(raw.infos);
  const messages = (Array.isArray(raw.messages) ? raw.messages : []).map(function (message) {
    const item = { severity: String(message.severity || 'info'), text: clip(message.text, MAX.text) };
    if (message.source_ref) item.source_ref = clip(message.source_ref, MAX.ref);
    return item;
  }).filter(function (item) { return item.text.length > 0; });
  if (messages.length) summary.messages = messages;
  return summary;
}

function networkOf(raw) {
  const summary = { requests: count(raw.requests), failures: count(raw.failures) };
  const entries = (Array.isArray(raw.entries) ? raw.entries : []).map(function (entry) {
    const item = { method: String(entry.method || ''), url_ref: String(entry.url_ref || ''), status: count(entry.status) };
    if (entry.resource_type) item.resource_type = String(entry.resource_type);
    if (count(entry.duration_ms) > 0) item.duration_ms = count(entry.duration_ms);
    if (count(entry.bytes) > 0) item.bytes = count(entry.bytes);
    return item;
  }).filter(function (item) { return item.url_ref.length > 0; });
  if (entries.length) summary.entries = entries;
  return summary;
}

function stepFrom(shard, order, seen) {
  const status = STATUSES[String(shard.status || '')] ? String(shard.status) : 'blocked';
  const step = { step_id: stepID(shard.step_id, order, seen), order: order, status: status };
  if (shard.title) step.title = clip(shard.title, MAX.text);
  if (shard.started_at) step.started_at = String(shard.started_at);
  if (shard.ended_at) step.ended_at = String(shard.ended_at);
  if (count(shard.duration_ms) > 0) step.duration_ms = count(shard.duration_ms);
  // screen_ref keys the gui.screen_matrix oracle; dropping it reports every screen missing.
  if (shard.screen_ref) step.screen_ref = clip(shard.screen_ref, MAX.ref);
  const summary = failureSummary(shard, status);
  if (summary) step.failure_summary = summary;
  if (Array.isArray(shard.actions) && shard.actions.length) step.actions = shard.actions.map(actionOf);
  if (shard.screenshot && shard.screenshot.ref) step.screenshot = mediaRefOf(shard.screenshot);
  if (shard.console) step.console = consoleOf(shard.console);
  if (shard.network) step.network = networkOf(shard.network);
  return step;
}

function listMediaFiles(root) {
  const found = [];
  let entries = [];
  try { entries = fs.readdirSync(root, { withFileTypes: true }); } catch (error) { return found; }
  entries.sort(function (left, right) { return compare(left.name, right.name); });
  entries.forEach(function (entry) {
    if (entry.isFile()) { found.push(entry.name); return; }
    if (!entry.isDirectory()) return;
    // Playwright writes per-test output into a subdirectory, so a video lands
    // one level below the directory the config points at.
    try {
      fs.readdirSync(path.join(root, entry.name)).sort().forEach(function (name) { found.push(entry.name + '/' + name); });
    } catch (nested) { return; }
  });
  return found;
}

function fileRef(dir, rel) {
  try {
    const body = fs.readFileSync(path.join(dir, rel));
    if (!body.length) return null;
    return { ref: rel, digest: 'sha256:' + crypto.createHash('sha256').update(body).digest('hex'), bytes: body.length, retention: 'local_only' };
  } catch (error) {
    return null;
  }
}

function collectMedia(policy, ids) {
  const media = [];
  [['trace', 'traces'], ['video', 'videos']].forEach(function (pair) {
    if (!policy.streams.includes(pair[0])) return;
    listMediaFiles(path.join(policy.dir, pair[1])).forEach(function (name) {
      if (media.length >= MAX.media) return;
      const entry = fileRef(policy.dir, pair[1] + '/' + name);
      if (!entry) return;
      entry.kind = pair[0];
      const owner = path.basename(name).replace(/\.[^.]+$/, '');
      if (ids[owner]) entry.step_id = owner;
      media.push(entry);
    });
  });
  return media;
}

// Replay is a pinned command, not synthesized code. Spec paths are the selector
// because an anchored title alternation would need the regex metacharacters the
// contract rejects, and the digest already pins what actually ran.
function buildReplay(policy, shards, rootDir) {
  if (policy.replayScript === 'off' || !shards.length) return null;
  const specs = [];
  shards.forEach(function (shard) {
    const ref = String(shard.spec_ref || '');
    if (!ref || path.isAbsolute(ref) || ref.indexOf('..') === 0 || ref.length > MAX.ref) return;
    if (specs.indexOf(ref) === -1) specs.push(ref);
  });
  specs.sort();
  const hash = crypto.createHash('sha256');
  const pinned = [];
  specs.slice(0, MAX.specs).forEach(function (ref) {
    // An unreadable spec cannot be pinned, so it leaves both the digest and the
    // command rather than describing a replay that would not reproduce.
    try { hash.update(fs.readFileSync(path.join(rootDir, ref))); } catch (error) { return; }
    pinned.push(ref);
  });
  if (!pinned.length) return null;
  const command = ['npm', 'exec', 'playwright', 'test', '--'].concat(pinned);
  if (!command.every(safeArg)) return null;
  return { kind: 'playwright-grep', command: command, spec_refs: pinned, digest: 'sha256:' + hash.digest('hex'), step_count: shards.length };
}

// computeTotals mirrors capture.ComputeTotals exactly: the Go validator rejects
// the index when the headline numbers disagree with the step evidence.
function computeTotals(steps, media) {
  const totals = { steps: steps.length, actions: 0, console_errors: 0, network_failures: 0, screenshots: 0, media_bytes: 0 };
  steps.forEach(function (step) {
    totals.actions += (step.actions || []).length;
    if (step.console) totals.console_errors += step.console.errors;
    if (step.network) totals.network_failures += step.network.failures;
    if (!step.screenshot) return;
    totals.screenshots += 1;
    totals.media_bytes += step.screenshot.bytes;
  });
  media.forEach(function (entry) { totals.media_bytes += entry.bytes; });
  return totals;
}

function writeIndex(policy, rootDir, startedAt, endedAt) {
  const shards = loadShards(policy.dir);
  const seen = {};
  const steps = shards.map(function (shard, position) { return stepFrom(shard, position + 1, seen); });
  const ids = {};
  steps.forEach(function (step) { ids[step.step_id] = true; });
  const media = collectMedia(policy, ids);
  const index = {
    schema_version: SCHEMA_VERSION,
    journey_id: policy.journeyId,
    mode: policy.mode,
    streams: policy.streams,
    started_at: startedAt,
    ended_at: endedAt,
    steps: steps,
  };
  if (media.length) index.media = media;
  const replay = buildReplay(policy, shards, rootDir);
  if (replay) index.replay = replay;
  index.totals = computeTotals(steps, media);
  const target = process.env[INDEX_PATH_ENV] || path.join(policy.dir, 'capture-index.json');
  fs.mkdirSync(path.dirname(target), { recursive: true });
  // Atomic publish: the harness reads the index as soon as the run exits.
  const temp = target + '.tmp-' + process.pid;
  fs.writeFileSync(temp, JSON.stringify(index, null, 2) + '\n');
  fs.renameSync(temp, target);
}

class AutopusCaptureReporter {
  constructor(options) {
    this.options = options || {};
    this.policy = null;
    this.rootDir = process.cwd();
    this.startedAt = '';
  }

  onBegin(config) {
    this.policy = safePolicy();
    if (config && config.rootDir) this.rootDir = config.rootDir;
    this.startedAt = new Date().toISOString();
  }

  onEnd() {
    if (!this.policy || this.policy.mode === 'off') return;
    try {
      writeIndex(this.policy, this.rootDir, this.startedAt, new Date().toISOString());
    } catch (error) {
      // Never fail the run from the reporter: the harness already fails closed
      // when capture-index.json is missing or malformed.
      process.stderr.write('autopus capture reporter failed: ' + String((error && error.message) || error) + '\n');
    }
  }
}

module.exports = AutopusCaptureReporter;
`
