package scaffold

import "strings"

// qaRuntimeGitignoreID is reported in the scaffold `created`/`skipped` lists.
const qaRuntimeGitignoreID = "qa-runtime-gitignore"

// qaRuntimeGitignoreStarter emits `.autopus/qa/.gitignore`.
//
// `auto qa run` deliberately keeps `runs/<id>/_raw/` after a run: those bytes are
// PRE-redaction, and `auto qa report --embed-media` plus local-only media resolve
// from them (see pkg/qa/capture.LocalCaptureDir). Retention without containment
// meant a user could commit a live AWS key, so the ignore file is the containment
// half of that contract. It is written through ensureStarter, so an existing file
// an operator has edited is preserved, never clobbered.
func qaRuntimeGitignoreStarter() starterFile {
	return starterFile{
		ID:      qaRuntimeGitignoreID,
		RelPath: ".autopus/qa/.gitignore",
		Reason:  "QA runtime tree retains pre-redaction bytes and machine-local caches",
		Body:    qaRuntimeGitignoreBody(),
	}
}

func qaRuntimeGitignoreBody() string {
	rows := []string{
		"# Autopus QAMESH runtime tree. Generated by `auto qa init`; edit freely.",
		"#",
		"# Paths below are machine-local or PRE-redaction and must never be committed.",
		"# Published evidence (manifest.json plus artifacts/) is redacted and stays",
		"# trackable, so it is not ignored here.",
		"",
		"# Pre-redaction capture bytes. `auto qa run` keeps them so `auto qa report",
		"# --embed-media` and local-only media can resolve; `auto qa release` deletes",
		"# them at the publish boundary. They contain secrets verbatim.",
		"_raw/",
		"",
		"# Harness-owned caches: Go build/module caches and the sandbox HOME that pack",
		"# commands see when a Journey Pack does not allowlist the real HOME.",
		"cache/",
		"",
		"# Runtime scratch written by GUI packs before the capture contract sanitizes it.",
		"gui/",
	}
	return strings.Join(rows, "\n") + "\n"
}
