package scaffold

// mobileScriptedStarter returns the project-local Maestro scripted Journey Pack
// starter emitted when Android or iOS signals are detected. The Body is a
// literal YAML document (carrying a mobile: block and source_refs that
// renderJourneyWithCWD does not emit) and must pass journey.Validate /
// validateMaestroPolicy: project-local .yaml flow under .autopus/qa/mobile,
// opaque device_target, and command argv matching mobile.flow_path.
func mobileScriptedStarter(signals projectSignals) starterFile {
	_ = signals // platform signals gate emission upstream; body is platform-agnostic
	return starterFile{
		ID:              "mobile-scripted-maestro",
		RelPath:         journeyRootRel + "/mobile-scripted-maestro.yaml",
		Reason:          "mobile project signals detected",
		Lanes:           []string{"mobile-scripted"},
		ValidateJourney: true,
		Body: `# Generated by auto qa init. Review before executing.
# ADK is a harness; this project-local Journey Pack owns the Maestro flow and device policy.
id: mobile-scripted-maestro
title: Mobile scripted Maestro lane
surface: mobile
lanes: [mobile-scripted]
adapter:
  id: maestro-scripted
command:
  argv: ["maestro", "test", ".autopus/qa/mobile/flows/smoke.yaml"]
  cwd: .
  timeout: 240s
checks:
  - id: mobile-scripted-maestro
    type: deterministic
    expected:
      exit_code: 0
mobile:
  flow_path: .autopus/qa/mobile/flows/smoke.yaml
  device_target: device-ref:local-emulator
  # @AX:NOTE: [AUTO] magic constant — placeholder digest; replace with real sha256 before executing the mobile-scripted lane
  app_artifact_digest: sha256:0000000000000000000000000000000000000000000000000000000000000000
source_refs:
  source_spec: SPEC-QAMESH-008
  acceptance_refs:
    - AC-QAMESH8-009
  owned_paths:
    - .
  do_not_modify_paths:
    - .codex/**
    - .opencode/**
    - .autopus/plugins/**
`,
	}
}
