package scaffold

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/insajin/autopus-adk/pkg/qa/journey"
	qaproject "github.com/insajin/autopus-adk/pkg/qa/project"
)

const (
	DesktopGUIJourneyID = "desktop-gui-explore"
	journeyRootRel      = ".autopus/qa/journeys"
)

type Options struct {
	ProjectDir string
}

type Result struct {
	Status     string       `json:"status"`
	ProjectDir string       `json:"project_dir"`
	Created    []FileResult `json:"created,omitempty"`
	Skipped    []FileResult `json:"skipped,omitempty"`
	Warnings   []string     `json:"warnings,omitempty"`
	NextSteps  []string     `json:"next_steps,omitempty"`
}

type FileResult struct {
	ID     string `json:"id"`
	Path   string `json:"path"`
	Reason string `json:"reason,omitempty"`
}

func Init(opts Options) (Result, error) {
	projectDir, err := normalizeProjectDir(opts.ProjectDir)
	if err != nil {
		return Result{}, err
	}
	result := Result{
		Status:     "noop",
		ProjectDir: projectDir,
	}
	if !qaproject.HasDesktopGUISignals(projectDir) {
		result.Warnings = []string{"no desktop GUI signals detected; auto qa init did not create a starter Journey Pack"}
		result.NextSteps = []string{"Run auto qa plan --format json to inspect existing project QA coverage."}
		return result, nil
	}
	path, err := desktopGUIJourneyPath(projectDir)
	if err != nil {
		return Result{}, err
	}
	file := FileResult{
		ID:   DesktopGUIJourneyID,
		Path: filepath.ToSlash(path),
	}
	if _, err := os.Stat(path); err == nil {
		file.Reason = "existing project-local Journey Pack preserved"
		result.Status = "skipped"
		result.Skipped = append(result.Skipped, file)
		result.NextSteps = initNextSteps()
		return result, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return Result{}, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return Result{}, err
	}
	if err := writeNewFile(path, []byte(desktopGUIJourneyYAML)); err != nil {
		return Result{}, err
	}
	pack, err := journey.LoadFile(path)
	if err != nil {
		return Result{}, err
	}
	if err := journey.Validate(pack, projectDir); err != nil {
		return Result{}, err
	}
	file.Reason = "desktop GUI target signals detected"
	result.Status = "created"
	result.Created = append(result.Created, file)
	result.NextSteps = initNextSteps()
	return result, nil
}

func normalizeProjectDir(value string) (string, error) {
	if strings.TrimSpace(value) == "" {
		value = "."
	}
	abs, err := filepath.Abs(value)
	if err != nil {
		return "", err
	}
	info, err := os.Stat(abs)
	if err != nil {
		return "", err
	}
	if !info.IsDir() {
		return "", fmt.Errorf("project dir is not a directory: %s", value)
	}
	real, err := filepath.EvalSymlinks(abs)
	if err != nil {
		return "", err
	}
	return real, nil
}

func desktopGUIJourneyPath(projectDir string) (string, error) {
	root := filepath.Join(projectDir, filepath.FromSlash(journeyRootRel))
	target := filepath.Join(root, DesktopGUIJourneyID+".yaml")
	rel, err := filepath.Rel(projectDir, target)
	if err != nil {
		return "", err
	}
	if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("journey path escapes project root")
	}
	return target, nil
}

func writeNewFile(path string, body []byte) error {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	defer file.Close()
	n, err := file.Write(body)
	if err != nil {
		return err
	}
	if n != len(body) {
		return io.ErrShortWrite
	}
	return nil
}

func initNextSteps() []string {
	return []string{
		"Review .autopus/qa/journeys/desktop-gui-explore.yaml for the real app command, origin, forbidden actions, and deterministic oracle.",
		"Run auto qa plan --lane gui-explore --format json before executing GUI exploration.",
	}
}

const desktopGUIJourneyYAML = `# Generated by auto qa init. Review before executing.
# ADK is a harness; this project-local Journey Pack owns product-specific GUI policy.
id: desktop-gui-explore
title: Desktop GUI exploration starter
surface: desktop
lanes: [gui-explore]
adapter:
  id: gui-explore
command:
  run: npm exec playwright test
  cwd: .
  timeout: 120s
checks:
  - id: desktop-gui-explore
    type: gui_exploration
artifacts:
  - kind: journey_graph
    path: .autopus/qa/gui/desktop-gui-explore/journey-graph.json
  - kind: aria_snapshot
    path: .autopus/qa/gui/desktop-gui-explore/a11y.aria.yml
  - kind: console_summary
    path: .autopus/qa/gui/desktop-gui-explore/console-summary.json
  - kind: network_summary
    path: .autopus/qa/gui/desktop-gui-explore/network-summary.json
  - kind: screenshot_quarantine_ref
    path: .autopus/qa/gui/desktop-gui-explore/screenshot-ref.json
gui:
  allowed_origins:
    - http://127.0.0.1:1420
  forbidden_actions:
    - mutation
    - payment
    - email_send
  selector_strategy: role-first
  network_policy:
    mode: local-only
  artifact_retention:
    publish_raw: false
source_refs:
  source_spec: SPEC-QAMESH-003
  acceptance_refs:
    - AC-QAMESH3-004
    - AC-QAMESH3-006
  owned_paths:
    - src/**
    - src-tauri/**
  do_not_modify_paths:
    - .codex/**
    - .opencode/**
    - .autopus/plugins/**
`
