package scaffold

import (
	"fmt"
	"strings"
)

func renderJourneyWithCWD(id, title, surface string, lanes []string, adapter string, argv []string, cwd string) string {
	if strings.TrimSpace(cwd) == "" {
		cwd = "."
	}
	return fmt.Sprintf(`# Generated by auto qa init. Review before executing.
# ADK is a harness; this project-local Journey Pack owns concrete commands and oracles.
# QAMESH owns evidence/release policy. Runner tools such as Playwright are adapters, not competing QA modes.
# Review command, origin, env, oracle, and artifact policy before --run.
id: %s
title: %s
surface: %s
lanes: [%s]
adapter:
  id: %s
command:
  argv: [%s]
  cwd: %s
  timeout: 240s
checks:
  - id: %s
    type: deterministic
    expected:
      exit_code: 0
source_refs:
  source_spec: %s
  acceptance_refs:
    - AC-QAMESH2-005
  owned_paths:
    - .
  do_not_modify_paths:
    - .codex/**
    - .opencode/**
    - .autopus/plugins/**
`, id, title, surface, renderInlineStrings(lanes), adapter, renderInlineStrings(argv), cwd, id, sourceSpecForLanes(lanes))
}

func canaryStarter() starterFile {
	return starterFile{
		ID:              "canary-explicit",
		RelPath:         journeyRootRel + "/canary-explicit.yaml",
		Reason:          "release mode requested",
		Lanes:           []string{"canary-explicit"},
		ValidateJourney: true,
		Body: `# Generated by auto qa init --release. Review before executing.
# This lane bridges an explicit post-deploy smoke command into auto qa release.
id: canary-explicit
title: Explicit post-deploy canary
surface: multi
lanes: [canary-explicit]
adapter:
  id: canary-template
command:
  argv: ["auto", "canary"]
  cwd: .
  timeout: 300s
checks:
  - id: canary-explicit
    type: smoke
    expected:
      exit_code: 0
artifacts:
  - kind: qamesh_ref
    path: .autopus/canary/latest.json
source_refs:
  source_spec: SPEC-QAMESH-004
  acceptance_refs:
    - AC-QAMESH4-001
  owned_paths:
    - .autopus/project/canary.md
    - .autopus/project/scenarios.md
  do_not_modify_paths:
    - .codex/**
    - .opencode/**
    - .autopus/plugins/**
`,
	}
}

func renderInlineStrings(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, ", ")
}

func sourceSpecForLanes(lanes []string) string {
	for _, lane := range lanes {
		switch lane {
		case "browser-staging", "desktop-native":
			return "SPEC-QAMESH-005"
		case "gui-explore":
			return "SPEC-QAMESH-003"
		case "canary-explicit":
			return "SPEC-QAMESH-004"
		}
	}
	return "SPEC-QAMESH-002"
}
