package scaffold

import (
	"fmt"
	"strings"
)

func renderJourney(id, title, surface string, lanes []string, adapter string, argv []string) string {
	return fmt.Sprintf(`# Generated by auto qa init. Review before executing.
# ADK is a harness; this project-local Journey Pack owns concrete commands and oracles.
id: %s
title: %s
surface: %s
lanes: [%s]
adapter:
  id: %s
command:
  argv: [%s]
  cwd: .
  timeout: 240s
checks:
  - id: %s
    type: deterministic
    expected:
      exit_code: 0
artifacts:
  - kind: stdout
    path: .autopus/qa/artifacts/%s/stdout.txt
  - kind: stderr
    path: .autopus/qa/artifacts/%s/stderr.txt
source_refs:
  source_spec: %s
  acceptance_refs:
    - AC-QAMESH2-005
  owned_paths:
    - .
  do_not_modify_paths:
    - .codex/**
    - .opencode/**
    - .autopus/plugins/**
`, id, title, surface, renderInlineStrings(lanes), adapter, renderInlineStrings(argv), id, id, id, sourceSpecForLanes(lanes))
}

func desktopGUIStarter() starterFile {
	return starterFile{
		ID:              DesktopGUIJourneyID,
		RelPath:         journeyRootRel + "/" + DesktopGUIJourneyID + ".yaml",
		Reason:          "desktop GUI target signals detected",
		ValidateJourney: true,
		Body: `# Generated by auto qa init. Review before executing.
# ADK is a harness; this project-local Journey Pack owns product-specific GUI policy.
id: desktop-gui-explore
title: Desktop GUI exploration starter
surface: desktop
lanes: [gui-explore]
adapter:
  id: gui-explore
command:
  argv: ["npm", "exec", "playwright", "test"]
  cwd: .
  timeout: 120s
checks:
  - id: desktop-gui-explore
    type: gui_exploration
artifacts:
  - kind: journey_graph
    path: .autopus/qa/gui/desktop-gui-explore/journey-graph.json
  - kind: aria_snapshot
    path: .autopus/qa/gui/desktop-gui-explore/a11y.aria.yml
  - kind: console_summary
    path: .autopus/qa/gui/desktop-gui-explore/console-summary.json
  - kind: network_summary
    path: .autopus/qa/gui/desktop-gui-explore/network-summary.json
  - kind: screenshot_quarantine_ref
    path: .autopus/qa/gui/desktop-gui-explore/screenshot-ref.json
gui:
  allowed_origins:
    - http://127.0.0.1:1420
  forbidden_actions:
    - mutation
    - payment
    - email_send
  selector_strategy: role-first
  network_policy:
    mode: local-only
  artifact_retention:
    publish_raw: false
source_refs:
  source_spec: SPEC-QAMESH-003
  acceptance_refs:
    - AC-QAMESH3-004
    - AC-QAMESH3-006
  owned_paths:
    - src/**
    - src-tauri/**
  do_not_modify_paths:
    - .codex/**
    - .opencode/**
    - .autopus/plugins/**
`,
	}
}

func canaryStarter() starterFile {
	return starterFile{
		ID:              "canary-explicit",
		RelPath:         journeyRootRel + "/canary-explicit.yaml",
		Reason:          "release mode requested",
		ValidateJourney: true,
		Body: `# Generated by auto qa init --release. Review before executing.
# This lane bridges an explicit post-deploy smoke command into auto qa release.
id: canary-explicit
title: Explicit post-deploy canary
surface: multi
lanes: [canary-explicit]
adapter:
  id: canary-template
command:
  argv: ["auto", "canary"]
  cwd: .
  timeout: 300s
checks:
  - id: canary-explicit
    type: smoke
    expected:
      exit_code: 0
artifacts:
  - kind: qamesh_ref
    path: .autopus/canary/latest.json
source_refs:
  source_spec: SPEC-QAMESH-004
  acceptance_refs:
    - AC-QAMESH4-001
  owned_paths:
    - .autopus/project/canary.md
    - .autopus/project/scenarios.md
  do_not_modify_paths:
    - .codex/**
    - .opencode/**
    - .autopus/plugins/**
`,
	}
}

func renderInlineStrings(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, fmt.Sprintf("%q", value))
	}
	return strings.Join(quoted, ", ")
}

func sourceSpecForLanes(lanes []string) string {
	for _, lane := range lanes {
		switch lane {
		case "browser-staging", "desktop-native":
			return "SPEC-QAMESH-005"
		case "gui-explore":
			return "SPEC-QAMESH-003"
		case "canary-explicit":
			return "SPEC-QAMESH-004"
		}
	}
	return "SPEC-QAMESH-002"
}
