package scaffold

import "strings"

func githubActionsWorkflowStarter(projectDir string) starterFile {
	signals := detectSignals(projectDir)
	return starterFile{
		ID:              "github-actions-release-gate",
		RelPath:         ".github/workflows/autopus-qa-release.yml",
		Reason:          "github-actions workflow requested",
		ValidateJourney: false,
		Body:            renderGitHubActionsWorkflow(signals),
	}
}

func renderGitHubActionsWorkflow(signals projectSignals) string {
	var steps []string
	steps = append(steps, `      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go for auto
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'

      - name: Install Autopus ADK
        run: |
          go install github.com/insajin/autopus-adk/cmd/auto@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
`)
	if signals.Stack == "go" {
		steps = append(steps, `
      - name: Download Go dependencies
        run: go mod download
`)
	}
	if signals.HasPackage {
		steps = append(steps, nodeSetupStep(signals))
	}
	if signals.Stack == "python" {
		steps = append(steps, pythonSetupStep())
	}
	if signals.Stack == "rust" {
		steps = append(steps, rustSetupStep())
	}
	if signals.HasPlaywright {
		steps = append(steps, `
      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps
`)
	}
	steps = append(steps, `
      - name: Inspect QAMESH release gate
        run: auto qa release --project-dir . --profile "$AUTOPUS_QA_PROFILE" --dry-run --format json

      - name: Run QAMESH release gate
        run: auto qa release --project-dir . --profile "$AUTOPUS_QA_PROFILE" --format json

      - name: Upload QAMESH evidence
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: qamesh-release
          path: .autopus/qa/
          retention-days: 14
`)
	return `# Generated by auto qa init. Review before requiring.
name: Autopus QA Release Gate

on:
  workflow_dispatch:
    inputs:
      profile:
        description: QAMESH release profile
        required: false
        default: release-candidate
  pull_request:
    branches: [main]
  push:
    tags:
      - 'v*'

jobs:
  qamesh-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    env:
      AUTOPUS_QA_PROFILE: ${{ github.event.inputs.profile || 'release-candidate' }}

    steps:
` + strings.Join(steps, "")
}

func nodeSetupStep(signals projectSignals) string {
	pm := signals.PackageManager
	install := "npm ci"
	cache := "npm"
	if pm == "pnpm" {
		install = "corepack enable && pnpm install --frozen-lockfile"
		cache = "pnpm"
	}
	if pm == "yarn" {
		install = "corepack enable && yarn install --immutable"
		cache = "yarn"
	}
	return `
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: ` + cache + `

      - name: Install Node dependencies
        run: ` + install + `
`
}

func pythonSetupStep() string {
	return `
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e .; fi
`
}

func rustSetupStep() string {
	return `
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
`
}
