package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/insajin/autopus-adk/pkg/adapter"
	"github.com/insajin/autopus-adk/pkg/config"
)

const legacyCodexProjectConfig = `# Codex configuration (auto-generated by Autopus-ADK)
# Project: legacy-project

model = "gpt-5.5"
model_reasoning_effort = "xhigh"

approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "cached"
project_doc_max_bytes = 262144
`

func TestCheckCodexModelOwnershipText_MigratableLegacyWarns(t *testing.T) {
	dir, cfg := writeLegacyCodexDoctorFixture(t, legacyCodexProjectConfig, true)
	var out bytes.Buffer

	ok := checkCodexModelOwnershipText(&out, dir, cfg)

	assert.False(t, ok)
	assert.Contains(t, out.String(), "Codex Model Ownership")
	assert.Contains(t, out.String(), "auto update")
	assert.Contains(t, out.String(), "new Codex session")
}

func TestCheckCodexModelOwnershipText_AmbiguousLegacyRequiresChoice(t *testing.T) {
	dir, cfg := writeLegacyCodexDoctorFixture(t, legacyCodexProjectConfig, false)
	var out bytes.Buffer

	ok := checkCodexModelOwnershipText(&out, dir, cfg)

	assert.False(t, ok)
	assert.Contains(t, out.String(), "auto quality supervisor inherit --apply")
	assert.Contains(t, out.String(), "auto quality supervisor quality --apply")
}

func TestCheckCodexModelOwnershipText_MissingManifestRequiresChoice(t *testing.T) {
	dir, cfg := writeLegacyCodexDoctorFixture(t, legacyCodexProjectConfig, true)
	require.NoError(t, os.Remove(filepath.Join(dir, ".autopus", "codex-manifest.json")))
	var out bytes.Buffer

	ok := checkCodexModelOwnershipText(&out, dir, cfg)

	assert.False(t, ok)
	assert.Contains(t, out.String(), "ambiguous legacy ownership")
	assert.Contains(t, out.String(), "auto quality supervisor inherit --apply")
}

func TestCheckCodexModelOwnershipText_UserOwnedAndExplicitPoliciesPass(t *testing.T) {
	tests := []struct {
		name    string
		content string
		policy  string
	}{
		{
			name: "user-owned marker",
			content: `# Codex configuration (auto-generated by Autopus-ADK)
# Autopus: user-owned Codex model settings: model, model_reasoning_effort
model = "custom/model"
model_reasoning_effort = "high"
`,
		},
		{
			name: "explicit inherit custom tuple",
			content: `# Codex configuration (auto-generated by Autopus-ADK)
model = "custom/model"
model_reasoning_effort = "high"
`,
			policy: config.SupervisorModelPolicyInherit,
		},
		{
			name:    "explicit inherit",
			content: "# Codex configuration (auto-generated by Autopus-ADK)\napproval_policy = \"on-request\"\n",
			policy:  config.SupervisorModelPolicyInherit,
		},
		{name: "explicit quality", content: legacyCodexProjectConfig, policy: config.SupervisorModelPolicyQuality},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir, cfg := writeLegacyCodexDoctorFixture(t, tt.content, true)
			cfg.Quality.SupervisorModelPolicy = tt.policy
			var out bytes.Buffer

			ok := checkCodexModelOwnershipText(&out, dir, cfg)

			assert.True(t, ok)
			assert.NotContains(t, out.String(), "auto quality supervisor")
			assert.NotContains(t, out.String(), "auto update")
		})
	}
}

func TestCheckCodexModelOwnershipText_ExplicitInheritWithStaleOverrideWarns(t *testing.T) {
	dir, cfg := writeLegacyCodexDoctorFixture(t, legacyCodexProjectConfig, true)
	cfg.Quality.SupervisorModelPolicy = config.SupervisorModelPolicyInherit
	var out bytes.Buffer

	ok := checkCodexModelOwnershipText(&out, dir, cfg)

	assert.False(t, ok)
	assert.Contains(t, out.String(), "inherit")
	assert.Contains(t, out.String(), "auto update")
}

func TestCheckCodexModelOwnershipText_ExplicitInheritWithPartiallyMarkedOverrideWarns(t *testing.T) {
	content := `# Codex configuration (auto-generated by Autopus-ADK)
# Autopus: user-owned Codex model settings: model
model = "gpt-5.5"
model_reasoning_effort = "xhigh"
`
	dir, cfg := writeLegacyCodexDoctorFixture(t, content, true)
	cfg.Quality.SupervisorModelPolicy = config.SupervisorModelPolicyInherit
	var out bytes.Buffer

	ok := checkCodexModelOwnershipText(&out, dir, cfg)

	assert.False(t, ok)
	assert.Contains(t, out.String(), "auto update")
}

func TestCheckCodexModelOwnershipText_NonCodexProjectSkips(t *testing.T) {
	cfg := config.DefaultFullConfig("claude-only")
	cfg.Platforms = []string{"claude-code"}
	var out bytes.Buffer

	ok := checkCodexModelOwnershipText(&out, t.TempDir(), cfg)

	assert.True(t, ok)
	assert.Contains(t, out.String(), "not applicable")
	assert.NotContains(t, out.String(), "auto update")
}

func TestCollectCodexModelOwnershipCheck_MigratableLegacyWarns(t *testing.T) {
	dir, cfg := writeLegacyCodexDoctorFixture(t, legacyCodexProjectConfig, true)
	report := doctorJSONReport{status: jsonStatusOK}

	report.collectCodexModelOwnershipCheck(dir, cfg)

	assert.Equal(t, jsonStatusWarn, report.status)
	require.Len(t, report.checks, 1)
	assert.Equal(t, "doctor.codex.supervisor_model_policy", report.checks[0].ID)
	assert.Equal(t, "warn", report.checks[0].Status)
	assert.Contains(t, report.checks[0].Detail, "auto update")
	require.Len(t, report.warnings, 1)
	assert.Equal(t, "legacy_codex_model_shadowing", report.warnings[0].Code)
}

func TestCodexModelOwnershipCheck_DoesNotModifyProjectFiles(t *testing.T) {
	dir, cfg := writeLegacyCodexDoctorFixture(t, legacyCodexProjectConfig, true)
	configPath := filepath.Join(dir, ".codex", "config.toml")
	harnessPath := filepath.Join(dir, "autopus.yaml")
	require.NoError(t, config.Save(dir, cfg))
	configBefore, err := os.ReadFile(configPath)
	require.NoError(t, err)
	harnessBefore, err := os.ReadFile(harnessPath)
	require.NoError(t, err)

	var out bytes.Buffer
	assert.False(t, checkCodexModelOwnershipText(&out, dir, cfg))
	report := doctorJSONReport{status: jsonStatusOK}
	report.collectCodexModelOwnershipCheck(dir, cfg)

	configAfter, err := os.ReadFile(configPath)
	require.NoError(t, err)
	harnessAfter, err := os.ReadFile(harnessPath)
	require.NoError(t, err)
	assert.Equal(t, configBefore, configAfter)
	assert.Equal(t, harnessBefore, harnessAfter)
}

func writeLegacyCodexDoctorFixture(t *testing.T, content string, currentMatchesManifest bool) (string, *config.HarnessConfig) {
	t.Helper()
	dir := t.TempDir()
	configPath := filepath.Join(dir, ".codex", "config.toml")
	require.NoError(t, os.MkdirAll(filepath.Dir(configPath), 0o755))
	require.NoError(t, os.WriteFile(configPath, []byte(content), 0o644))

	checksum := adapter.Checksum(content)
	if !currentMatchesManifest {
		checksum = adapter.Checksum("previous generated content")
	}
	manifest := adapter.NewManifest("codex")
	manifest.Files[filepath.ToSlash(filepath.Join(".codex", "config.toml"))] = adapter.ManifestFile{
		Checksum: checksum,
		Policy:   adapter.OverwriteMerge,
	}
	require.NoError(t, manifest.Save(dir))

	cfg := config.DefaultFullConfig("legacy-project")
	cfg.Platforms = []string{"codex"}
	cfg.Quality.SupervisorModelPolicy = ""
	return dir, cfg
}
