package scenario

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// StarterID is the example scenario 'auto qa scenario init' writes.
const StarterID = "first-visit"

// StarterBody renders an example scenario for a project. It is an example, not
// a working assertion set: the harness does not know what this product renders,
// so the emitted steps are the shape to edit rather than coverage to trust.
func StarterBody(journeyID, origin string) string {
	if strings.TrimSpace(journeyID) == "" {
		journeyID = "browser-gui-explore"
	}
	originLine := "# origin: http://127.0.0.1:4173   # inherited from the journey's allowed_origins when unset"
	if strings.TrimSpace(origin) != "" {
		originLine = fmt.Sprintf("# origin: %s   # inherited from the journey's allowed_origins when unset", origin)
	}
	return fmt.Sprintf(`# Generated by 'auto qa scenario init'. Edit before relying on it.
#
# A scenario is the project's own statement of what a user sees. 'auto qa
# scenario compile' turns it into a Playwright spec under the project's testDir
# so the declaration becomes executable evidence.
#
# The step vocabulary is read-only on purpose: expect_title, expect_url,
# expect_text, expect_role, expect_count. click, fill, and press are not
# representable, so a compiled scenario can never trip the gui-explore
# forbidden-action guard. Write mutating flows as hand-authored specs instead.
#
# Elements are addressed by ARIA role, matching the pack's
# 'selector_strategy: role-first'. An unknown key or unknown role rejects the
# whole file rather than silently dropping the assertion.
schema_version: %s
id: %s
title: A first-time visitor reaches the landing page
journey: %s
%s
# acceptance_refs: [AC-001]        # optional: link back to acceptance.md
screens:
  - id: landing
    path: /
    steps:
      - expect_title: EDIT-ME
      - expect_role:
          role: heading
      # - expect_role:
      #     role: heading
      #     name: Welcome
      #     exact: true
      # - expect_text: Get started
      # - expect_url: /
      # - expect_count:
      #     role: listitem
      #     count: 3
`, SchemaVersion, StarterID, journeyID, originLine)
}

// WriteStarter creates the example scenario. It never overwrites: the file is
// project-owned once written, and clobbering authored assertions would destroy
// the only record of what the project decided to cover.
func WriteStarter(projectDir, journeyID, origin string) (path string, created bool, err error) {
	dir := Dir(projectDir)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", false, err
	}
	target := filepath.Join(dir, StarterID+".yaml")
	if _, statErr := os.Stat(target); statErr == nil {
		return target, false, nil
	}
	if err := os.WriteFile(target, []byte(StarterBody(journeyID, origin)), 0o644); err != nil {
		return "", false, err
	}
	return target, true, nil
}
