package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/insajin/autopus-adk/pkg/adapter"
)

func (a *Adapter) cleanupDeprecatedSurface(files []adapter.FileMapping) error {
	if err := a.cleanupPluginWorkflowShims(); err != nil {
		return err
	}
	if err := a.cleanupUnexpectedPluginSkills(files); err != nil {
		return err
	}
	return a.cleanupLegacyRootConfig()
}

func (a *Adapter) cleanupPluginWorkflowShims() error {
	for _, spec := range workflowSpecs {
		if spec.Name == "auto" {
			continue
		}
		target := filepath.Join(a.root, ".autopus", "plugins", "auto", "skills", spec.Name)
		if err := os.RemoveAll(target); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("deprecated Codex plugin shim 제거 실패 %s: %w", target, err)
		}
	}
	return nil
}

func (a *Adapter) cleanupUnexpectedPluginSkills(files []adapter.FileMapping) error {
	if len(files) == 0 {
		return nil
	}

	pluginSkillsRoot := filepath.ToSlash(filepath.Join(".autopus", "plugins", "auto", "skills"))
	expected := make(map[string]bool)
	for _, file := range files {
		target := filepath.ToSlash(file.TargetPath)
		if !strings.HasPrefix(target, pluginSkillsRoot+"/") {
			continue
		}
		rest := strings.TrimPrefix(target, pluginSkillsRoot+"/")
		name := strings.Split(rest, "/")[0]
		if name != "" {
			expected[name] = true
		}
	}

	root := filepath.Join(a.root, ".autopus", "plugins", "auto", "skills")
	entries, err := os.ReadDir(root)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("Codex plugin skill surface 읽기 실패 %s: %w", root, err)
	}

	for _, entry := range entries {
		if expected[entry.Name()] {
			continue
		}
		target := filepath.Join(root, entry.Name())
		if err := os.RemoveAll(target); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("stale Codex plugin skill 제거 실패 %s: %w", target, err)
		}
	}
	return nil
}

func (a *Adapter) cleanupLegacyRootConfig() error {
	target := filepath.Join(a.root, "config.toml")
	data, err := os.ReadFile(target)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return nil
	}
	if !strings.Contains(string(data), "auto-generated by Autopus-ADK") {
		return nil
	}
	if err := os.Remove(target); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("deprecated Codex root config 제거 실패 %s: %w", target, err)
	}
	return nil
}

func (a *Adapter) cleanupStaleManagedSurfaces(oldManifest *adapter.Manifest, files []adapter.FileMapping, backupDir *string) error {
	if oldManifest == nil {
		return nil
	}
	diff := adapter.BuildManifestDiff(oldManifest, files, codexPruneRoots())
	return adapter.PruneManagedPaths(a.root, diff.Prune, backupDir)
}

func codexPruneRoots() []string {
	return []string{
		filepath.ToSlash(filepath.Join(".codex", "skills")),
		filepath.ToSlash(filepath.Join(".autopus", "plugins", "auto", "skills")),
	}
}
