package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/insajin/autopus-adk/pkg/adapter"
)

func (a *Adapter) cleanupDeprecatedSurface() error {
	if err := a.cleanupPluginWorkflowShims(); err != nil {
		return err
	}
	return a.cleanupLegacyRootConfig()
}

func (a *Adapter) cleanupPluginWorkflowShims() error {
	for _, spec := range workflowSpecs {
		if spec.Name == "auto" {
			continue
		}
		target := filepath.Join(a.root, ".autopus", "plugins", "auto", "skills", spec.Name)
		if err := os.RemoveAll(target); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("deprecated Codex plugin shim 제거 실패 %s: %w", target, err)
		}
	}
	return nil
}

func (a *Adapter) cleanupLegacyRootConfig() error {
	target := filepath.Join(a.root, "config.toml")
	data, err := os.ReadFile(target)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return nil
	}
	if !strings.Contains(string(data), "auto-generated by Autopus-ADK") {
		return nil
	}
	if err := os.Remove(target); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("deprecated Codex root config 제거 실패 %s: %w", target, err)
	}
	return nil
}

func (a *Adapter) cleanupStaleManagedSurfaces(oldManifest *adapter.Manifest, files []adapter.FileMapping, backupDir *string) error {
	if oldManifest == nil {
		return nil
	}
	diff := adapter.BuildManifestDiff(oldManifest, files, codexPruneRoots())
	return adapter.PruneManagedPaths(a.root, diff.Prune, backupDir)
}

func codexPruneRoots() []string {
	return []string{
		filepath.ToSlash(filepath.Join(".codex", "skills")),
		filepath.ToSlash(filepath.Join(".autopus", "plugins", "auto", "skills")),
	}
}
