package codex

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/insajin/autopus-adk/pkg/adapter"
	"github.com/insajin/autopus-adk/pkg/config"
)

func (a *Adapter) buildUpdateTransactionPlan(
	cfg *config.HarnessConfig,
	oldManifest *adapter.Manifest,
	newFiles []adapter.FileMapping,
) (adapter.TransactionPlan, *adapter.PlatformFiles, error) {
	finalFiles := make([]adapter.FileMapping, 0, len(newFiles))
	writes := make([]adapter.TransactionWrite, 0, len(newFiles))

	for _, file := range newFiles {
		action := adapter.ResolveAction(a.root, file.TargetPath, file.OverwritePolicy, oldManifest)
		if action == adapter.ActionSkip {
			continue
		}
		finalFiles = append(finalFiles, file)
		writes = append(writes, adapter.TransactionWrite{
			Path:    file.TargetPath,
			Content: file.Content,
			Perm:    codexFileMode(file.TargetPath),
		})
	}

	removes, err := a.buildUpdateTransactionRemoves(oldManifest, newFiles)
	if err != nil {
		return adapter.TransactionPlan{}, nil, err
	}

	pf := &adapter.PlatformFiles{
		Files:    finalFiles,
		Checksum: checksum(fmt.Sprintf("%d", len(finalFiles))),
	}
	manifest := adapter.ManifestFromFiles(adapterName, filterCodexManifestFiles(cfg, pf))
	plan := adapter.TransactionPlan{
		Writes:   writes,
		Removes:  removes,
		Manifest: manifest,
	}
	return plan, pf, nil
}

func (a *Adapter) buildUpdateTransactionRemoves(
	oldManifest *adapter.Manifest,
	files []adapter.FileMapping,
) ([]adapter.TransactionRemove, error) {
	var removes []adapter.TransactionRemove
	if oldManifest != nil {
		diff := adapter.BuildManifestDiff(oldManifest, files, codexPruneRoots())
		for _, entry := range diff.Prune {
			removes = append(removes, adapter.TransactionRemove{Path: entry.Path})
		}
	}
	removes = append(removes, a.pluginWorkflowShimRemoves()...)

	unexpected, err := a.unexpectedPluginSkillRemoves(files)
	if err != nil {
		return nil, err
	}
	removes = append(removes, unexpected...)

	if remove, ok := a.legacyRootConfigRemove(); ok {
		removes = append(removes, remove)
	}
	return adapter.FilterUnsupportedRootGitHookRemoves(a.root, removes), nil
}

func (a *Adapter) pluginWorkflowShimRemoves() []adapter.TransactionRemove {
	removes := make([]adapter.TransactionRemove, 0, len(workflowSpecs))
	for _, spec := range workflowSpecs {
		if spec.Name == "auto" {
			continue
		}
		removes = append(removes, adapter.TransactionRemove{
			Path:      filepath.Join(".autopus", "plugins", "auto", "skills", spec.Name),
			Recursive: true,
		})
	}
	return removes
}

func (a *Adapter) unexpectedPluginSkillRemoves(files []adapter.FileMapping) ([]adapter.TransactionRemove, error) {
	if len(files) == 0 {
		return nil, nil
	}

	pluginSkillsRoot := filepath.ToSlash(filepath.Join(".autopus", "plugins", "auto", "skills"))
	expected := make(map[string]bool)
	for _, file := range files {
		target := filepath.ToSlash(file.TargetPath)
		if !strings.HasPrefix(target, pluginSkillsRoot+"/") {
			continue
		}
		rest := strings.TrimPrefix(target, pluginSkillsRoot+"/")
		name := strings.Split(rest, "/")[0]
		if name != "" {
			expected[name] = true
		}
	}

	root := filepath.Join(a.root, ".autopus", "plugins", "auto", "skills")
	entries, err := os.ReadDir(root)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("Codex plugin skill surface 읽기 실패 %s: %w", root, err)
	}

	var removes []adapter.TransactionRemove
	for _, entry := range entries {
		if expected[entry.Name()] {
			continue
		}
		removes = append(removes, adapter.TransactionRemove{
			Path:      filepath.Join(".autopus", "plugins", "auto", "skills", entry.Name()),
			Recursive: true,
		})
	}
	return removes, nil
}

func (a *Adapter) legacyRootConfigRemove() (adapter.TransactionRemove, bool) {
	target := filepath.Join(a.root, "config.toml")
	data, err := os.ReadFile(target)
	if err != nil || !strings.Contains(string(data), "auto-generated by Autopus-ADK") {
		return adapter.TransactionRemove{}, false
	}
	return adapter.TransactionRemove{Path: "config.toml"}, true
}

func codexFileMode(path string) os.FileMode {
	clean := filepath.ToSlash(path)
	if adapter.IsRootGitHookPath(clean) || strings.HasSuffix(clean, ".sh") {
		return 0755
	}
	return 0644
}
