package opencode

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	contentfs "github.com/insajin/autopus-adk/content"
	"github.com/insajin/autopus-adk/pkg/adapter"
	"github.com/insajin/autopus-adk/pkg/config"
	pkgcontent "github.com/insajin/autopus-adk/pkg/content"
	"github.com/insajin/autopus-adk/templates"
)

var markerRe = regexp.MustCompile(`(?s)` + regexp.QuoteMeta(markerBegin) + `.*?` + regexp.QuoteMeta(markerEnd))

// agentsMDTemplate is the AGENTS.md AUTOPUS section template used when
// opencode owns the root document. Opencode wins the arbitration whenever it
// is installed alongside codex: codexOwnsRootDoc returns false in that case
// and the codex adapter drops its AGENTS.md mapping, so this marker replaces
// the whole section. The platform-independent policy comes from the shared
// fragments so the two markers cannot drift apart; only the installed path
// list, execution model, and OpenCode notes are opencode-specific.
var agentsMDTemplate = `# Autopus-ADK Harness

> 이 섹션은 Autopus-ADK에 의해 자동 생성됩니다. 수동으로 편집하지 마세요.

- **프로젝트**: {{.ProjectName}}
- **모드**: {{.Mode}}
- **플랫폼**: {{join ", " .Platforms}}

` + templates.RootDocInstalledComponents() + `

` + templates.RootDocPolicy() + `

## Execution Model

{{if contains (join ", " .Platforms) "codex"}}- **Codex V2**: multi_agent_v2 uses spawn_agent, send_message, followup_task, wait_agent, interrupt_agent, list_agents.
- **Codex Workspace**: 모든 agent는 shared cwd/filesystem을 사용합니다. fork_turns는 대화 context만 분기하며 filesystem isolation이나 merge를 제공하지 않습니다.
- **Codex Router**: @auto <route> ...는 auto plugin을 호출하고 상세 workflow는 $codex-auto-<route> skill로 라우팅합니다.
- **Codex /goal**: Codex goals feature를 사용합니다. @auto goal은 이 기능의 thin wrapper이며, active goal이 있으면 get_goal로 목표를 반영하고 create_goal/update_goal은 Codex goal tool contract를 만족할 때만 사용하세요.
{{end}}{{if contains (join ", " .Platforms) "opencode"}}- **OpenCode**: 기본 실행 모델은 task(...) 기반 subagent-first 입니다.
- **OpenCode Invocation**: /auto <subcommand> ... 또는 /auto-<subcommand> ... alias를 사용합니다.
{{end}}

## OpenCode Notes

- The generated rules are loaded through opencode.json instructions.
- Runtime plugins are registered through the plugin field in opencode.json.
- Use /auto <subcommand> ... or direct aliases like /auto-plan ... .
- Default OpenCode session model is assumed to be openai/gpt-5.4; users can override with opencode -m <provider/model> or opencode run -m <provider/model>.
- Use --variant <value> for provider-specific reasoning effort overrides when needed.
- Project skills are published under .agents/skills/ so OpenCode can load them through the native skill tool.{{if contains (join ", " .Platforms) "codex"}} If you want a smaller mixed Codex + OpenCode surface, set skills.shared_surface to "auto" or "core" to reduce Codex workspace noise.{{end}}
- A dedicated OpenCode statusline surface is not generated by default; use CLI wrappers like auto status and auto doctor for observability.

## Core Guidelines

` + templates.RootDocGuidelines() + `
`

func (a *Adapter) prepareAgentsMapping(cfg *config.HarnessConfig) (adapter.FileMapping, error) {
	content, err := a.injectMarkerSection(cfg)
	if err != nil {
		return adapter.FileMapping{}, err
	}
	return adapter.FileMapping{
		TargetPath:      "AGENTS.md",
		OverwritePolicy: adapter.OverwriteMarker,
		Checksum:        adapter.Checksum(content),
		Content:         []byte(content),
	}, nil
}

func (a *Adapter) injectMarkerSection(cfg *config.HarnessConfig) (string, error) {
	path := filepath.Join(a.root, "AGENTS.md")
	cfg = ensurePlatformInRootDoc(cfg, "opencode")
	var existing string
	if data, err := os.ReadFile(path); err == nil {
		existing = string(data)
	}

	section, err := a.engine.RenderString(agentsMDTemplate, cfg)
	if err != nil {
		return "", fmt.Errorf("AGENTS.md 템플릿 렌더링 실패: %w", err)
	}
	agentsSection, err := renderAgentsSection()
	if err != nil {
		return "", err
	}
	section += agentsSection
	section += "\n## Rules\n\n"
	if containsPlatform(cfg.Platforms, "codex") {
		section += "See .codex/skills/codex-agent-pipeline/SKILL.md for Codex phase and gate contracts.\n"
		section += "See .codex/skills/codex-<name>/SKILL.md for Codex-native workflow skills.\n"
		section += "See .codex/agents/ for Codex agent definitions.\n"
	}
	if containsPlatform(cfg.Platforms, "opencode") {
		section += "See .opencode/rules/autopus/ for OpenCode guidance.\n"
	}
	newSection := markerBegin + "\n" + section + "\n" + markerEnd

	if strings.Contains(existing, markerBegin) && strings.Contains(existing, markerEnd) {
		return markerRe.ReplaceAllStringFunc(existing, func(string) string { return newSection }), nil
	}
	if existing == "" {
		return newSection + "\n", nil
	}
	return existing + "\n\n" + newSection + "\n", nil
}

func renderAgentsSection() (string, error) {
	entries, err := contentfs.FS.ReadDir("agents")
	if err != nil {
		return "", fmt.Errorf("agents 디렉터리 읽기 실패: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("\n## Agents\n\n")
	sb.WriteString("The following specialized agents are available.\n\n")
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".md") {
			continue
		}
		data, readErr := fs.ReadFile(contentfs.FS, pkgcontent.EmbeddedPath("agents", entry.Name()))
		if readErr != nil {
			return "", fmt.Errorf("agent 파일 읽기 실패 %s: %w", entry.Name(), readErr)
		}
		name, desc := extractAgentMeta(string(data), entry.Name())
		fmt.Fprintf(&sb, "### %s\n\n", name)
		if desc != "" {
			sb.WriteString(desc)
			sb.WriteString("\n\n")
		}
	}
	return sb.String(), nil
}

func extractAgentMeta(content string, fallback string) (string, string) {
	_, body := splitFrontmatter(content)
	if strings.TrimSpace(body) == "" {
		body = content
	}
	name := strings.TrimSuffix(fallback, filepath.Ext(fallback))
	var desc string
	for _, line := range strings.Split(body, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if strings.HasPrefix(trimmed, "# ") {
			name = strings.TrimPrefix(trimmed, "# ")
			continue
		}
		desc = trimmed
		break
	}
	return name, desc
}

func containsPlatform(platforms []string, target string) bool {
	for _, platform := range platforms {
		if platform == target {
			return true
		}
	}
	return false
}

func ensurePlatformInRootDoc(cfg *config.HarnessConfig, platform string) *config.HarnessConfig {
	if cfg == nil {
		return nil
	}
	if containsPlatform(cfg.Platforms, platform) {
		return cfg
	}
	cloned := *cfg
	cloned.Platforms = append(append([]string{}, cfg.Platforms...), platform)
	return &cloned
}

func removeMarkerSection(content string) string {
	cleaned := strings.TrimSpace(markerRe.ReplaceAllString(content, ""))
	if cleaned == "" {
		return ""
	}
	return cleaned + "\n"
}
