package content

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/insajin/autopus-adk/pkg/workflow"
)

const (
	workflowsSubdir       = "workflows"
	routeASchemaFile      = "route_a.schema.json"
	routeAMarkdown        = "route_a.md"
	routeAJSTmplName      = "route_a.workflow.js.tmpl"
	routeTeamSchemaFile   = "route_team.schema.json"
	routeTeamMarkdown     = "route_team.md"
	routeTeamJSTmplName   = "route_team.workflow.js.tmpl"
	gateBuildTestID       = "gate_build_test"
	releaseHygieneID      = "release_hygiene"
	generatedJSHeader     = "// GENERATED by auto generate-templates from content/workflows/route_a.{md,schema.json} — DO NOT EDIT. Edit the manifest SoT instead."
	generatedTeamJSHeader = "// GENERATED by auto generate-templates from content/workflows/route_team.{md,schema.json} — DO NOT EDIT. Edit the manifest SoT instead."
)

// generateWorkflowTemplates derives the claude workflow JS templates from the
// manifest sources of truth (route_a + route_team), runs the parity gate per
// route, and on success writes templates/claude/workflows/<route>.workflow.js.tmpl.
//
// Check-before-write: if a route's parity gate fails, that route's JS template
// is NOT written or updated, and the divergence error is returned. Routes whose
// manifest is absent are skipped silently, keeping generation backward-compatible
// with content trees that predate a given route.
func generateWorkflowTemplates(contentDir, templateDir string) error {
	if err := generateOneRoute(contentDir, templateDir,
		routeASchemaFile, routeAMarkdown, routeAJSTmplName,
		generatedJSHeader, deriveWorkflowJS); err != nil {
		return err
	}
	if err := generateOneRoute(contentDir, templateDir,
		routeTeamSchemaFile, routeTeamMarkdown, routeTeamJSTmplName,
		generatedTeamJSHeader, deriveTeamWorkflowJS); err != nil {
		return err
	}
	return nil
}

// generateOneRoute generates a single workflow route from its manifest. The
// header argument is unused for derivation (each derive function embeds its own
// header) but kept in the signature to document the route's generated header and
// allow future header-injection without changing call sites. If the schema file
// is absent the route is skipped silently (os.Stat IsNotExist).
func generateOneRoute(contentDir, templateDir, schemaFile, mdFile, jsTmplName, header string, derive func(workflow.Schema) string) error {
	_ = header // header is embedded by the derive function; documented per route.
	schemaPath := filepath.Join(contentDir, workflowsSubdir, schemaFile)
	mdPath := filepath.Join(contentDir, workflowsSubdir, mdFile)

	if _, statErr := os.Stat(schemaPath); os.IsNotExist(statErr) {
		return nil
	}

	schema, err := workflow.LoadSchema(schemaPath)
	if err != nil {
		return fmt.Errorf("load workflow schema: %w", err)
	}
	mdBytes, err := os.ReadFile(mdPath)
	if err != nil {
		return fmt.Errorf("read workflow markdown %q: %w", mdPath, err)
	}

	derivedJS := derive(schema)

	if err := checkWorkflowParity(parityArtifacts{
		schema:     schema,
		derivedJS:  derivedJS,
		markdownMD: string(mdBytes),
	}); err != nil {
		// Fail-closed: do not write the JS template on drift.
		return err
	}

	outDir := filepath.Join(templateDir, "claude", workflowsSubdir)
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("create workflows template dir: %w", err)
	}
	if err := validateName(jsTmplName); err != nil {
		return fmt.Errorf("workflow template name: %w", err)
	}
	outPath := filepath.Join(outDir, jsTmplName)
	if err := os.WriteFile(outPath, []byte(derivedJS), 0644); err != nil {
		return fmt.Errorf("write workflow template %q: %w", outPath, err)
	}
	return nil
}

// deriveWorkflowJS produces the deterministic JS workflow template from the
// schema. Phase order equals schema array order. No timestamps, no randomness;
// the output is a pure function of the schema.
func deriveWorkflowJS(schema workflow.Schema) string {
	var sb strings.Builder

	sb.WriteString(generatedJSHeader)
	sb.WriteString("\n//\n")
	sb.WriteString("// route-a deterministic workflow adapter. The manifest (route_a.md +\n")
	sb.WriteString("// route_a.schema.json) is the source of truth; this file is regenerated.\n\n")

	// meta literal with ordered phase titles.
	sb.WriteString("export const meta = {\n")
	sb.WriteString("  name: 'route-a',\n")
	sb.WriteString("  description: 'Deterministic opt-in Route A workflow (planning -> implementation -> gate -> release hygiene).',\n")
	sb.WriteString("  phases: [\n")
	for _, p := range schema.Phases {
		fmt.Fprintf(&sb, "    {title:'%s'},\n", p.ID)
	}
	sb.WriteString("  ],\n")
	sb.WriteString("};\n\n")

	// Script body: one phase(...) call per schema phase, in order.
	sb.WriteString("// Workflow API globals: agent, phase, log.\n")
	sb.WriteString("export default async function run() {\n")
	for _, p := range schema.Phases {
		writePhaseBlock(&sb, p)
	}
	sb.WriteString("}\n")

	return sb.String()
}

// writePhaseBlock emits a deterministic phase(...) block. The gate and release
// hygiene phases shell out to CLI checks so JS owns sequencing, not verdict
// policy.
func writePhaseBlock(sb *strings.Builder, p workflow.PhaseDef) {
	fmt.Fprintf(sb, "  await phase('%s', { retry: %d, budget: %d }, async () => {\n", p.ID, p.Retry, p.Budget)
	if p.ID == gateBuildTestID {
		fmt.Fprintf(sb, "    // Deterministic gate: verdict_source '%s'. Shell out to the\n", p.ResultType)
		sb.WriteString("    // `auto workflow gate` CLI (JS->Go bridge) and parse its JSON.\n")
		sb.WriteString("    const out = await agent.exec(['auto', 'workflow', 'gate']);\n")
		sb.WriteString("    const gate = JSON.parse(out.stdout);\n")
		sb.WriteString("    log('gate', gate.verdict, gate.verdict_source, gate.build_exit, gate.test_exit);\n")
		sb.WriteString("    if (gate.verdict !== 'pass') {\n")
		sb.WriteString("      throw new Error('gate failed: ' + gate.verdict_source);\n")
		sb.WriteString("    }\n")
	} else if p.ID == releaseHygieneID {
		sb.WriteString("    // Release hygiene: generated/runtime drift + staged source size gate.\n")
		sb.WriteString("    const out = await agent.exec(['auto', 'check', '--hygiene', '--arch', '--quiet', '--staged']);\n")
		sb.WriteString("    log('release_hygiene', 'pass', out.stdout);\n")
	} else {
		fmt.Fprintf(sb, "    log('phase', '%s');\n", p.ID)
	}
	sb.WriteString("  });\n")
}
