package rulecond

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"
)

// ManifestVersion is the compiled conditional manifest schema version.
const ManifestVersion = "1"

// Manifest is the compiled conditional rule manifest. It is generated by the
// compiler and read by the dispatcher, and it is untrusted at read time because
// a cloned repository can ship its own copy.
type Manifest struct {
	Version string         `json:"version"`
	Rules   []ManifestRule `json:"rules"`
}

// ManifestRule is one compiled hook-fired rule.
type ManifestRule struct {
	// Name is the rule name, which is also the injection header and the
	// ordering key.
	Name string `json:"name"`
	// Event is the hook event the rule fires on.
	Event string `json:"event"`
	// Matcher is the Claude Code tool matcher the rule fires on.
	Matcher string `json:"matcher"`
	// Conditions are the RE2 regexes matched against the condition subject.
	Conditions []string `json:"conditions"`
	// Body is the rule body location relative to the conditional body root.
	// REQ-CONDRULE-COMPILE-07 forbids storing an absolute path here.
	Body string `json:"body"`
}

// encodeManifest renders the manifest with rules ordered by rule name and with
// stable key ordering, so regeneration produces no spurious diff
// (REQ-CONDRULE-COMPILE-04). Struct field order fixes the key order.
func encodeManifest(rules []ManifestRule) ([]byte, error) {
	sorted := make([]ManifestRule, len(rules))
	copy(sorted, rules)
	sort.SliceStable(sorted, func(i, j int) bool {
		if sorted[i].Name != sorted[j].Name {
			return sorted[i].Name < sorted[j].Name
		}
		return sorted[i].Matcher < sorted[j].Matcher
	})

	blob, err := json.MarshalIndent(Manifest{Version: ManifestVersion, Rules: sorted}, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(blob, '\n'), nil
}

// Bounds on the untrusted manifest read. Exceeding either one is treated as a
// malformed manifest, which is fail-open for the whole run: no injection, no
// diagnostic, exit zero (REQ-CONDRULE-FIRE-03).
//
// @AX:NOTE [AUTO] @AX:SPEC: SPEC-CONDRULE-001: the manifest is repo-supplied, so its size and rule count are attacker-chosen; an unbounded read or an unbounded rule list makes the dispatcher a memory-exhaustion target on every tool call.
const (
	// maxManifestBytes bounds the manifest read, matching the 1 MiB bound the
	// dispatcher already applies to the hook stdin payload.
	maxManifestBytes = 1 << 20
	// maxManifestRules bounds how many rules one manifest may declare. The
	// shipped manifest carries three; 256 leaves generous headroom while
	// keeping the per-tool-call regex compilation cost bounded.
	maxManifestRules = 256
)

// ruleNamePattern constrains the manifest Name field to a bare, bounded
// identifier. Name is not merely an ordering key: it is rendered into the
// injected context header and into the truncation notice, so an unconstrained
// value is attacker-controlled model context. The character set is symmetric
// with the compile-side constraints in checkCompiledBody, which already refuse
// an empty name, a path separator, and a `..` component.
var ruleNamePattern = regexp.MustCompile(`^[a-zA-Z0-9._-]{1,64}$`)

// sanitizeName renders an untrusted rule name safe for a one-line stderr
// diagnostic: every character outside the accepted set becomes `?` and the
// result is truncated, so a huge or newline-bearing name can neither flood
// stderr nor forge additional "<rule> <reason>" lines.
func sanitizeName(name string) string {
	const maxReported = 64
	var b strings.Builder
	for _, r := range name {
		if b.Len() >= maxReported {
			break
		}
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9',
			r == '.', r == '_', r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('?')
		}
	}
	if b.Len() == 0 {
		return "?"
	}
	return b.String()
}

// manifestDiagnosticName is the fixed token a run-level fail-closed refusal is
// reported under. It occupies the rule-name column of the stderr line because
// the failure precedes any rule being known.
const manifestDiagnosticName = "conditional-rules"

// loadManifest reads the manifest from manifestPath, which MUST come from
// ResolveManifestPath. No environment variable, flag, or stdin field can
// redirect it (REQ-CONDRULE-FIRE-11).
//
// Every field of the decoded manifest is untrusted. Rules whose Name fails
// ruleNamePattern are dropped here and returned separately so the caller can
// report them fail-closed per rule, leaving every conforming rule injectable.
func loadManifest(manifestPath string) (Manifest, []string, error) {
	data, err := readManifestFile(manifestPath)
	if err != nil {
		return Manifest{}, nil, err
	}
	var manifest Manifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return Manifest{}, nil, err
	}
	if len(manifest.Rules) > maxManifestRules {
		return Manifest{}, nil, fmt.Errorf("manifest declares %d rules, above the %d cap",
			len(manifest.Rules), maxManifestRules)
	}

	kept := make([]ManifestRule, 0, len(manifest.Rules))
	var rejected []string
	for _, rule := range manifest.Rules {
		if !ruleNamePattern.MatchString(rule.Name) {
			rejected = append(rejected, sanitizeName(rule.Name))
			continue
		}
		kept = append(kept, rule)
	}
	manifest.Rules = kept
	return manifest, rejected, nil
}

// readManifestFile reads the manifest under maxManifestBytes. A file above the
// bound returns an error rather than a truncated document, so an oversize
// manifest fails open instead of decoding into a partial rule set.
func readManifestFile(path string) ([]byte, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	data, err := io.ReadAll(io.LimitReader(file, maxManifestBytes+1))
	if err != nil {
		return nil, err
	}
	if len(data) > maxManifestBytes {
		return nil, fmt.Errorf("manifest exceeds the %d byte cap", maxManifestBytes)
	}
	return data, nil
}
